##### 共通設定 #####
[DEFAULT.filter]
id       = "^(?!YarCraft|weapon_anvil)"
naming   = "m"
category = "^(axe|blunt|dagger|martial|polearm|scythe|shield|staff|sword)$"
quality  = "0"

[DEFAULT.recipe]
id.prefix  = "YarCraft"
id.suffix  = [ "wood", "stone", "metal", "cloth" ]
variant    = [ "log", "rock", "ingot", "texture" ]
factory    = [ "factory_wood", "factory_stone", "anvil", "loom" ]
defMat     = [ "oak", "granite", "iron", "cotton" ]
tierGroup  = [ "metal", "metal", "metal", "leather" ]
recipeKey  = "{'*' if int(line['LV']) <= 10 else ''}"
tag        = "{line['tag'] + ',noDrop,noShop' if line['tag'] else 'noDrop,noShop'}"
components = "{variant}/{int((w:=int(line['weight']))/500+1)},resin/{int(w/1000+1)},string/{int(w/2000+1)},money/{int((v:=int(line['value']))/100+1)}"
