##### 共通設定 #####
[DEFAULT.filter]
id      = "^(?!YarCraft)"
naming  = "m"
factory = "^\\s*$"
quality = "0"

[DEFAULT.recipe]
id.prefix = "YarCraft"
id.suffix = [ "wood", "stone", "metal", "cloth" ]
variant   = [ "log", "rock", "ingot", "texture" ]
factory   = [ "factory_wood", "factory_stone", "factory_metal", "loom" ]
defMat    = [ "oak", "granite", "iron", "cotton" ]
tierGroup = [ "metal", "metal", "metal", "leather" ]
recipeKey = "{'*' if int(line['LV']) <= 10 else ''}"
tag       = "{line['tag'] + ',noDrop,noShop' if line['tag'] else 'noDrop,noShop'}"

##### 個別設定(兜) #####
["helm"]
filter.name       = "^helm$"
filter.category   = "^head$"
recipe.components = "{variant},+rune"

["feather hat"]
filter.name       = "^feather hat$"
filter.category   = "^head$"
recipe.components = "{variant},texture,+rune"

["wizard hat"]
filter.name       = "^wizard hat$"
filter.category   = "^head$"
recipe.components = "{variant},texture,+rune"

["knight helm"]
filter.name       = "^knight helm$"
filter.category   = "^head$"
recipe.components = "{variant}/2,+rune"

["heavy helm"]
filter.name       = "^heavy helm$"
filter.category   = "^head$"
recipe.components = "{variant}/2,+rune"

["fairy hat"]
filter.name       = "^fairy hat$"
filter.category   = "^head$"
recipe.components = "{variant},texture,+rune"

["composite helm"]
filter.name       = "^composite helm$"
filter.category   = "^head$"
recipe.components = "{variant}/2,+rune"

["great helm"]
filter.name       = "^great helm$"
filter.category   = "^head$"
recipe.components = "{variant}/3,+rune"

##### 個別設定(体) #####
["robe"]
filter.name       = "^robe$"
filter.category   = "^torso$"
recipe.components = "{variant},texture,resin,string,+rune"

["breastplate"] # バニラと競合しないように
filter.name       = "^breastplate$"
filter.category   = "^torso$"
filter.factory    = ".*"
recipe.components = "{variant}/3,resin/4,bone/2,+rune"
recipe.id.suffix  = [ "wood", "metal", "cloth" ]
recipe.variant    = [ "log", "ingot", "texture" ]
recipe.factory    = [ "factory_wood", "factory_metal", "loom" ]
recipe.defMat     = [ "oak", "iron", "cotton" ]
recipe.tierGroup  = [ "metal", "metal", "leather" ]

["shirt"]
filter.name       = "^shirt$"
filter.category   = "^torso$"
recipe.components = "{variant},texture,string,resin,+rune"

["light mail"]
filter.name       = "^light mail$"
filter.category   = "^torso$"
recipe.components = "{variant}/2,texture,string,resin/2,+rune"

["banded mail"]
filter.name       = "^banded mail$"
filter.category   = "^torso$"
recipe.components = "{variant}/5,texture/2,string,resin/4,bone/2,+rune"

["coat"]
filter.name       = "^coat$"
filter.category   = "^torso$"
recipe.components = "{variant}/2,texture,string,resin/2,bone,+rune"

["ring mail"]
filter.name       = "^ring mail$"
filter.category   = "^torso$"
recipe.components = "{variant}/4,texture/2,string,resin/3,bone/2,+rune"

["great armor"]
filter.name       = "^great armor$"
filter.category   = "^torso$"
recipe.components = "{variant}/5,texture/2,string,resin/4,bone/2,+rune"

["composite mail"]
filter.name       = "^composite mail$"
filter.category   = "^torso$"
recipe.components = "{variant}/4,texture/2,string,resin/3,bone/2,+rune"

["bulletproof jacket"]
filter.name       = "^bulletproof jacket$"
filter.category   = "^torso$"
recipe.components = "{variant}/2,texture/2,string,resin/2,bone,+rune"

["chain mail"]
filter.name       = "^chain mail$"
filter.category   = "^torso$"
recipe.components = "{variant}/4,texture/2,string,resin/3,bone/2,+rune"

["pope robe"]
filter.name       = "^pope robe$"
filter.category   = "^torso$"
recipe.components = "{variant}/2,texture,string,resin,+rune"

["plate mail"]
filter.name       = "^plate mail$"
filter.category   = "^torso$"
recipe.components = "{variant}/6,texture/2,string/2,resin/6,bone/2,+rune"

##### 個別設定(腰) #####
["girdle"] # バニラと競合しないように
filter.name       = "^girdle$"
filter.category   = "^waist$"
filter.factory    = ".*"
recipe.components = "{variant}/3,fiber/3|texture,needle/2,+rune"
recipe.id.suffix  = [ "wood", "metal", "cloth" ]
recipe.variant    = [ "log", "ingot", "texture" ]
recipe.factory    = [ "factory_wood", "factory_metal", "loom" ]
recipe.defMat     = [ "oak", "iron", "cotton" ]
recipe.tierGroup  = [ "metal", "metal", "leather" ]

["composite girdle"]
filter.name       = "^composite girdle$"
filter.category   = "^waist$"
recipe.components = "{variant}/2,fiber/3|texture,needle/2,+rune"

["plate girdle"]
filter.name       = "^plate girdle$"
filter.category   = "^waist$"
recipe.components = "{variant}/3,ingot,fiber/3|texture,needle/2,+rune"

##### 個別設定(手) #####
["light gloves"] # バニラと競合しないように
filter.name       = "^light gloves$"
filter.category   = "^arm$"
filter.factory    = ".*"
recipe.components = "{variant},texture,needle/2,+rune"

["thick gauntlets"]
filter.name       = "^thick gauntlets$"
filter.category   = "^arm$"
recipe.components = "{variant},fiber/3|texture,needle,+rune"

["composite gauntlets"]
filter.name       = "^composite gauntlets$"
filter.category   = "^arm$"
recipe.components = "{variant}/2,fiber/3|texture,needle,+rune"

["gloves"]
filter.name       = "^gloves$"
filter.category   = "^arm$"
recipe.components = "{variant},fiber/3|texture,needle,+rune"

["plate gauntlets"]
filter.name       = "^plate gauntlets$"
filter.category   = "^arm$"
recipe.components = "{variant}/2,ingot,fiber/3|texture,needle/2,+rune"

["decorated gloves"]
filter.name       = "^decorated gloves$"
filter.category   = "^arm$"
recipe.components = "{variant},fiber/3|texture,needle/2,+rune"

["great gauntlets"]
filter.name       = "^plate$"
filter.category   = "^arm$"
recipe.components = "{variant}/2,ingot,fiber/3|texture,needle/2,+rune"
